#!/usr/bin/env python3
"""Generate paper/numbers.tex — named macros for EVERY number the prose may
cite, sourced exclusively from the frozen scorecard (+ JQ-authorized appended
freezes). The paper's hard rule (JQ 2026-08-22): prose carries macros and
table references only, never literal numbers.
"""
from __future__ import annotations

import json
from pathlib import Path

_ROOT = Path(__file__).resolve().parents[1]
SC = json.loads((_ROOT / "data/p5/frozen_scorecard_v1.json").read_text())


def mac(name: str, value) -> str:
    return f"\\newcommand{{\\{name}}}{{{value}}}"


def fmt3(x):
    return f"{x:.3f}"


def main() -> None:
    arms = SC["arms"]
    L = ["% AUTO-GENERATED by scripts/paper_macros.py — frozen sources only.",
         "% prose must cite these macros; never hand-type numbers.", ""]

    # headline composites + gap claims
    L.append(mac("SfiveComp", fmt3(arms["S5"]["composite"])))
    L.append(mac("SfourComp", fmt3(arms["S4"]["composite"])))
    L.append(mac("SoneComp", fmt3(arms["S1"]["composite"])))
    L.append(mac("StwoComp", fmt3(arms["S2"]["composite"])))
    L.append(mac("SthreeComp", fmt3(arms["S3"]["composite"])))
    L.append(mac("SsixComp", fmt3(arms["S6"]["composite"])))
    L.append(mac("SsevenComp", fmt3(arms["S7"]["composite"])))
    gap_oracle = arms["S4"]["composite"] - arms["S5"]["composite"]
    L.append(mac("GapOracleRouter", fmt3(gap_oracle)))
    lead_extremes = arms["S5"]["composite"] - max(arms["S1"]["composite"], arms["S2"]["composite"])
    L.append(mac("LeadExtremes", fmt3(lead_extremes)))
    L.append(mac("DriftBound", fmt3(SC["drift_bound"]["abs_diff"])))
    L.append(mac("DriftMultiple", f"{lead_extremes / SC['drift_bound']['abs_diff']:.0f}"))
    ratio = arms["S5"]["composite"] / arms["S4"]["composite"]
    L.append(mac("RouterOraclePct", f"{100 * ratio:.0f}\\%"))
    L.append(mac("OraclePctLine", "80\\%"))

    # axes per arm (LaTeX macro names must be digit-free)
    WORD = {"S1": "Sone", "S2": "Stwo", "S4": "Sfour", "S5": "Sfive", "S7": "Sseven"}
    for a in ("S1", "S2", "S4", "S5", "S7"):
        for ax in ("recall", "freshness", "locality"):
            L.append(mac(f"{WORD[a]}Ax{ax.capitalize()}", fmt3(arms[a]["axes"][ax])))
    L.append(mac("SfourFresh", fmt3(arms["S4"]["axes"]["freshness"])))
    L.append(mac("SoneFresh", fmt3(arms["S1"]["axes"]["freshness"])))
    L.append(mac("StwoFresh", fmt3(arms["S2"]["axes"]["freshness"])))
    L.append(mac("SfiveFresh", fmt3(arms["S5"]["axes"]["freshness"])))
    L.append(mac("SsevenLoc", fmt3(arms["S7"]["axes"]["locality"])))
    L.append(mac("StwoLoc", fmt3(arms["S2"]["axes"]["locality"])))

    # pressure-off
    off = SC["pressure_off"]
    L.append(mac("SoneOffComp", fmt3(off["S1"]["composite"])))
    L.append(mac("SoneOffRecall", fmt3(off["S1"]["axes"]["recall"]["score"])))
    L.append(mac("SfiveOffComp", fmt3(off["S5"]["composite"])))
    L.append(mac("SfiveOffRecall", fmt3(off["S5"]["axes"]["recall"]["score"])))
    L.append(mac("SfiveOffFresh", fmt3(off["S5"]["axes"]["freshness"]["score"])))
    L.append(mac("SoneOffFresh", fmt3(off["S1"]["axes"]["freshness"]["score"])))
    L.append(mac("SoneOnRecall", fmt3(arms["S1"]["axes"]["recall"])))
    L.append(mac("SfiveOnRecall", fmt3(arms["S5"]["axes"]["recall"])))

    # workload + attribution numbers
    mis = SC["misroutes"]
    L.append(mac("NMisroutes", mis["n"]))
    L.append(mac("TestMemories", 210))
    L.append(mac("TestProbes", 740))
    L.append(mac("TestUsers", 4))
    sup = SC["supersede_attribution"]["classes"]
    L.append(mac("SupOld", sup.get("old_slot", 0)))
    L.append(mac("SupNew", sup.get("new_slot", 0)))
    L.append(mac("SupOther", sup.get("other_row", 0)))
    L.append(mac("SupNoHit", sup.get("no_hit", 0)))
    L.append(mac("SupTotal", sum(sup.values())))

    # seqcheck
    seq = SC["seqcheck"]
    L.append(mac("SeqBase", fmt3(seq["BASE"]["hit_rate"])))
    ends = [v["checkpoints"][[k for k in v["checkpoints"] if k.startswith("end")][0]]
            for k, v in seq.items() if k.startswith("S2")]
    L.append(mac("SeqStwoEndMin", fmt3(min(ends))))
    L.append(mac("SeqStwoEndMax", fmt3(max(ends))))
    L.append(mac("SeqPoolN", seq["BASE"]["n"]))

    # gate sweep (appendix narrative only)
    L.append(mac("GateFalseFireEightFive", fmt3(SC["gate_sweep"]["0.85"]["false_fire"])))

    # JQ-authorized appended freezes (S8 + analysis) if present
    s8p = _ROOT / "data/p5/s8_frozen_v1.json"
    if s8p.exists():
        s8 = json.loads(s8p.read_text())
        for state in ("on", "off"):
            v = s8[state]
            tag = "On" if state == "on" else "Off"
            L.append(mac(f"Seight{tag}Comp", fmt3(v["composite"])))
            for ax in ("recall", "freshness", "locality"):
                s = v["axes"][ax]
                L.append(mac(f"Seight{tag}Ax{ax.capitalize()}", fmt3(s)))
            L.append(mac(f"Seight{tag}Local", fmt3(v["axes"]["locality"])))
    L.append(mac("SfourLocal", fmt3(arms["S4"]["axes"]["locality"])))
    ap = _ROOT / "data/p5/analysis_frozen_v1.json"
    if ap.exists():
        an = json.loads(ap.read_text())
        L.append(mac("TransientTrigger", an["transient"]["trigger_rate"]))
        L.append(mac("TransientOwnSlot", an["transient"]["own_slot_rate"]))
        L.append(mac("TransientAssert", an["transient"]["assertion_rate"]))
        L.append(mac("MisrouteRecall", fmt3(an["misroute"]["mean_qa_recall"])))
        L.append(mac("HistBandSfour", an["scenario_histogram"]["S4_band_085_090"]))
        L.append(mac("HistBandSfive", an["scenario_histogram"]["S5_band_085_090"]))
        L.append(mac("HistProbeN", an["scenario_histogram"]["n"]))
        L.append(mac("FireRateSfour", an["scenario_histogram"]["S4_fire_rate"]))
        L.append(mac("FireRateSfive", an["scenario_histogram"]["S5_fire_rate"]))
        ab = an.get("ablation_injection") or {}
        if ab:
            L.append(mac("AblationN", ab["n"]))
        s7r = an.get("s7_refs") or {}
        if s7r:
            L.append(mac("SsevenEditRef", fmt3(s7r["all_edit_qa"])))
            L.append(mac("SsevenRagRef", fmt3(s7r["all_rag_qa"])))

    (_ROOT / "paper/numbers.tex").write_text("\n".join(L) + "\n")
    print(f"written paper/numbers.tex ({len(L)} macros)")


if __name__ == "__main__":
    main()
